config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :articles do
    resources :likes, only: %i[create destroy]
  end

  root 'articles#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, class_name: 'ArticleLike', dependent: :destroy

  validates :title, length: { minimum: 3, maximum: 255 }, presence: true
  validates :body, length: { minimum: 200 }, presence: true
end

app/models/article_like.rb
# frozen_string_literal: true

class ArticleLike < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: :likes_count

  validates :user_id, uniqueness: { scope: :article_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :article_likes, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_admin

  private

  def user_not_admin
    redirect_to root_path
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @articles = Article.includes(:user)
  end

  def show
    @like = current_user&.article_likes&.find_by(article_id: @article.id)
  end

  def new
    @article = Article.new
    authorize @article
  end

  def edit
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    authorize @article
    @article.user = current_user

    if @article.save
      redirect_to @article, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end


  def update
    authorize @article
    if @article.update(article_params)
      redirect_to @article, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @article
    @article.destroy

    redirect_to root_path, notice: t('.success')
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @article = Article.find(params[:article_id])
    @like = @article.likes.find_or_create_by(user: current_user)

    redirect_to(article_path(@article))
  end

  def destroy
    @article = Article.find(params[:article_id])
    @like = @article.likes.find(params[:id])

    @like.destroy if @like.user == current_user

    redirect_to(article_path(@article))
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/articles/_form.html.slim
  = simple_form_for @article do |f|
    .mb-4
      = f.input :title,
        input_html: { class: 'form-control form-control-lg' },
        wrapper_html: { class: 'form-group' },
        label_html: { class: 'form-label fs-5' }

    .mb-4
      = f.input :body,
        as: :text,
        input_html: { class: 'form-control', rows: 5 },
        wrapper_html: { class: 'form-group' },
        label_html: { class: 'form-label fs-5' }

    .d-flex.gap-3.mt-5
      = f.submit class: 'btn btn-primary btn-lg flex-grow-1'
      - if controller.action_name == 'edit'
        = link_to t('.back'), article_path(@article), class: 'btn btn-outline-secondary btn-lg flex-grow-1'

app/views/articles/edit.html.slim
.container.mt-5
.shadow.p-4.bg-white.rounded
  = render 'form'

app/views/articles/index.html.slim
h1.mb-4 = t('.title')

.list-group
  - @articles.each do |article|
    .list-group-item.mb-3.shadow-sm
      .d-flex.flex-column
        h4.mb-2 = link_to article.title, article_path(article)
        p.text-muted.mb-3 = truncate(article.body, length: 200, separator: ' ')
        .align-self-end
        span.i.bi.bi-hand-thumbs-up.me-2 = article.likes.count

app/views/articles/new.html.slim
.container.mt-5
  h1.mb-4.text-center = t('.title')
  .shadow.p-4.bg-white.rounded
    = render 'form'

app/views/articles/show.html.slim
.row.justify-content-center
  .col-md-8
    .card.shadow
      .card-header.bg-light
        h1.mb-0.text-center = @article.title

      .card-body
        .article-content.fs-5.mb-4
          = @article.body

        #likes-section.d-flex.align-items-center.justify-content-start.mb-3
          = render 'likes/like', article: @article, like: @like
          span.me-2 = @article.likes.count

        - if current_user&.admin?
          .mt-4.d-flex.justify-content-end
            = link_to t('.button.edit'), edit_article_path, class: 'btn btn-warning me-2'
            = link_to t('.button.delete'), article_path, data: { turbo_method: :delete }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || 'Second Test Task'
    meta name='viewport' content='width=device-width,initial-scale=1'
    meta name='apple-mobile-web-app-capable' content='yes'
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel='manifest' href='/manifest.json'
    link rel='icon' href='/icon.png' type='image/png'
    link rel='icon' href='/icon.svg' type='image/svg+xml'
    link rel='apple-touch-icon' href='/icon.png'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body.d-flex.flex-column.h-100
    = render 'shared/navbar'
    = render 'shared/flash'

    main
      .container.mt-5
        = yield

app/views/likes/_like.html.slim
- if user_signed_in?
  - if current_user && @like
    = link_to article_like_path(@article, @like),
      data: { turbo_method: :delete }, class: 'btn' do
        i.bi.bi-hand-thumbs-up-fill
  - else
    = link_to article_likes_path(@article),
      data: { turbo_method: :post }, class: 'btn' do
        i.bi.bi-hand-thumbs-up
- else
  i.bi.bi-hand-thumbs-up

app/views/shared/_flash.html.slim
- if flash[:notice]
  .container
    .alert.alert-info.alert-dismissible.fade.show role="alert" data-controller="flash"
      = flash[:notice]
      button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"
- if flash[:alert]
  .container
    .alert.alert-danger.alert-dismissible.fade.show role="alert" data-controller="flash"
      = flash[:alert]
      button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.bg-body-tertiary
  .container-fluid
    a = link_to t('.title'), root_path, class: 'navbar-brand'
    button.navbar-toggler type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        - if user_signed_in?
          - if current_user.admin?
            li.nav-item
              = link_to t('.add_article'), new_article_path, class: 'nav-link active aria-current'
          li.nav-item
            a.nav-link = current_user.email
          = link_to t('.sign_out'), destroy_user_session_path, data: { turbo_method: :delete },
            class: 'nav-link active aria-current'
        - else
          = link_to t('.sign_in'), new_user_session_path, class: 'nav-link active aria-current'